import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ModeToggle";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  regularPayments,
  costPrediction,
}: {
  children: React.ReactNode;
  regularPayments: React.ReactNode;
  costPrediction: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="container mx-auto p-4">
            <header className="flex justify-between items-center p-4">
              <h1 className="text-2xl font-bold">Payment Management</h1>
              {/* <ModeToggle /> */}
            </header>
            <Tabs defaultValue="regular" className="w-full">
              <TabsList>
                <TabsTrigger value="regular">
                  Regular Payments
                </TabsTrigger>
                <TabsTrigger value="prediction">
                  Cost Prediction
                </TabsTrigger>
              </TabsList>
              <TabsContent value="regular">
                {regularPayments}
              </TabsContent>
              <TabsContent value="prediction">
                {costPrediction}
              </TabsContent>
            </Tabs>
            {/* {children} */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
